host:
  # web api host
  # you can use API and Web interface through this host
  # webapi: docker.dev.example.net
  webapi: docker.wakateweb.konboi.com

  # host suffix
  # if you access to foo.dev.example.net, mirage search "foo" subdomain container
  reverse_proxy_suffix: .wakateweb.konboi.com

listen:
  # listen address
  # default is only listen from localhost
  foreign_address: 127.0.0.1

  # listen port and reverse proxy port
  http:
    # listen 8080 and transport to container's 5000 port
    - listen: 5580
      target: 4567

  # not implemented
  # we recommend to use frontend http(like nginx) to SSL termination
  # HTTPS:
  #   - 443

docker:
  # if you use docker through http, specify like "http://localhost:4243"
  endpoint: unix:///var/run/docker.sock

  # if you specify this, fill the form as default value on web interface.
  default_image: "wakateweb:latest"